server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password: sushant1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    sql-show: true


logging:
  level:
    org.springframework.security: DEBUG

security:
  jwt:
    #key must be greater than 64 length for HS256algorithm
    secret: ${JWT_SECRET:mysecretkeymysecretkeymysecretkeymysecretkeymysecretkeymysecretkey}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}
